OEL-160: Drupal 9 compatibility fixes.
openeuropa/multivalue_form_element pull request #9
Opened 2021-05-27 13:41 UTC by saidatom

2021-05-27 13:55 UTC, claudiu-cristea requested changes

2021-05-27 13:55 UTC, claudiu-cristea commented on composer.json
> +        "phpunit/phpunit": "^7 || ^8"
Why is ^9 not added? Drupal 9 knows to run with PHPUnit 9

2021-05-27 13:55 UTC, claudiu-cristea commented on tests/src/Functional/RequiredElementsTest.php
> +    $this->assertSession()->responseContains('Baz field is required.');
What is the reason for this change? Is it something that has changed in the way the module works? Keep in mind that `::responseContains()` is checking the page source while `::pageTextContains()` only in visible text. So, I think the later is more appropriate in this case.

2021-05-27 13:55 UTC, claudiu-cristea commented on tests/src/Functional/RequiredElementsTest.php
> +    $this->assertSession()->responseNotContains('Bar field is required.');
Same here: `::pageTextNotContains()`

2021-05-27 16:06 UTC, claudiu-cristea commented
Leaving here a note: The last commit d6f76e1 is to ensure that the module can be installed also on Drupal 8.9. Until that:
- `phpspec/prophecy-phpunit": "^2"` enforced PHPUnit 9
- PHPUnit 9 enforced Drupal 9.

2021-05-27 16:06 UTC, claudiu-cristea approved these changes, later dismissed

2021-05-31 11:17 UTC, upchuk requested changes
* The phpunit dist misses the cache result check: https://github.com/openeuropa/rdf_skos/pull/69/files#diff-e35810879ec42bdd81797b3ccb72f6de28a8b4a0e3bfdba43183e133e866b892R2

2021-06-16 09:57 UTC, brummbar requested changes

2021-06-16 09:57 UTC, brummbar commented on composer.json
> +        "drupal/drupal-extension": "~4.0",
This was 4.1 minimum, is there a reason to lower it? Let's convert it to ^ also.

2021-06-16 09:57 UTC, brummbar commented on composer.json
> +        "openeuropa/behat-transformation-context": "~0.1",
Why this was added? It's not used.

2021-06-16 09:57 UTC, brummbar commented on composer.json
> +        "openeuropa/code-review": "~1.6",
Let's use ^.

2021-06-16 09:57 UTC, brummbar commented on multivalue_form_element.info.yml
>  core_version_requirement: ^8 || ^9
Since we are now putting compatibility to ^8.9 || ^9.1 in composer.json, we can reflect that here.

2021-06-16 09:57 UTC, brummbar commented on tests/modules/multivalue_form_element_test/multivalue_form_element_test.info.yml
>  core_version_requirement: ^8 || ^9
Since we are now putting compatibility to ^8.9 || ^9.1 in composer.json, we can reflect that here.

2021-06-29 11:48 UTC, brummbar approved these changes

2021-06-29 11:49 UTC, upchuk approved these changes

2021-06-29 11:53 UTC, merged